### ISSUE TITLE
rake db:drop doesn't work with PostgreSQL with no username and password

### ISSUE THREAD

**Issue by elspethsoup** [TalentBox/sequel-rails#10]
Environment:
ruby: 1.9.3-p327
rails: 3.2.11
sequel version: 3.43.0
sequel-rails version: 0.4.0.pre1
database: PostgreSQL 9.2

My database.yml looks like this:

``` yaml
development:
  adapter: postgresql
  database: mobiledb_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: mobiledb_test
  pool: 5
  timeout: 5000
```

When I run `rake db:drop` I get this:

```
dropdb: could not connect to database template1: FATAL:  no PostgreSQL user name
 specified in startup packet
[sequel] Dropped database 'mobiledb_development'
```

Rake also, thinks the rake task succeeded, but the database is still there.
