### ISSUE TITLE
Invalid JDBC URL generated from database.yml

### ISSUE THREAD

**Issue by mrbrdo** [TalentBox/sequel-rails#35]
database.yml

```
production:
  adapter: postgresql
  encoding: unicode
  url: "jdbc:postgresql://HOST/DB?user=U&password=P&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory"
  pool: 5
  min_messages: WARNING
```

(this is what I use for a Heroku hosted DB, and app is not hosted on Heroku)

This config works with ActiveRecord JDBC.

sequel-rails generates an url that looks something like this (from my head, can't find exact value atm):
`jdbc:postgresql:////?encoding=uncode&uri=jdbc:postgresql://HOST/DB?user=U&password=P&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory`

With this URL, Sequel will not complain, but it works as if you connected to an empty database (e.g. db.tables is [], etc).

For my case I temporarily solved by:

``` ruby
  conf = YAML::load(File.read(Rails.root.join('config/database.yml')))["production"]
  Sequel::Model.db = Sequel.connect adapter: 'jdbc',
    uri: conf['url'],
    encoding: conf['encoding'],
    max_connections: conf['pool']
```
